### PR TITLE
Toggle line numbers in code blocks

### PR DESCRIPTION
**Pull request by Et3rnos**
I added a new field to `MuiMarkdown` and `getOverrides` called `showLineNumbers`.

I was actually not able to test it because `npm build-lib` and then `npm link`ing were throwing some errors when I tried to test it from another project. Is this how you usually test it or was I doing something wrong?

### CODE REVIEW

**Comment by HPouyanmehr** [comment]
Hey @Et3rnos,

Thanks for the attribute you've added. That will be helpful. Changes generally look fine. I will comment on the lines that I think can be changed.

And for the test, I'm also using the `npm link` 

You can follow this steps, and that should be ok:
1. Run `npm run build-lib` to build the changes.
2. Run `npm link` in the project root.
3. In the other sample project try to install the package using `npm link mui-markdown` command.

**Comment by Et3rnos** [comment]
Thanks for the response, I'll look forward to your comments then.

Also, looks like the error I'm getting was because some packages were being loaded twice, one from the library itself and one from my test project, not sure how to fix it though because I do need the devDependencies to be able to build the library... I guess I'll give it another try later, if you ever came across the same problem I would love to hear what you did to circumvent it.

**Comment by HPouyanmehr** [comment]
Thank you @Et3rnos for the contribution. I've merged your changes and did change the keyword. (I think it's better to say `hideLineNumber` rather than `showLineNumbers={false}`)

Install the latest version ([`1.1.2`](https://github.com/HPouyanmehr/mui-markdown/releases/tag/v1.1.2)) to have the code blocks without number.

For testing the changes, It is better to have a clean and fresh react app to avoid conflicts. Also, providing more details about the error or having a test repo would help. Currently, It's hard to understand the issue you have.

**Comment by Et3rnos** [comment]
Yep, `hideLineNumber` makes more sense, yes.

> Install the latest version ([1.1.2](https://github.com/HPouyanmehr/mui-markdown/releases/tag/v1.1.2)) to have the code blocks without number.

Thanks, will do.

I'll be putting the testing issue aside for now, until I decide to contribute to this project again, don't want to bug you too much :)

**Comment by Et3rnos** [comment]
By the way @HPouyanmehr, I did notice you didn't keep my README changes.

However, the `getOverrides()` calls in your examples do not work with the new version, so you might want to change them:

image

As you can see, the last one fails.

EDIT: Actually, only 1 of the 4 examples have the new syntax, you probably forgot to update the others?

**Comment by HPouyanmehr** [comment]
Yeah, that's a bug, and you're right. 
Sorry about your changes in the README file. I didn't mean to ignore your effort. I just tried to reorder your changes and update the keyword. The issue about `getOverrides()` occurred due to my hurry. I tried to stabilize the changes you need faster to publish the package and make it available sooner because I have limited free time during the week.

Thank you for your suggestion about the code block. I appreciate it! You're always welcome to make more contributions.

About the `getOverrides`:
Having an issue will help to track and fix it. Generally, I think it's better to have that like `getOverrides()` rather than `getOverrides({})` as it is more readable, and the curly braces are useless here. What do you think?

**Comment by Et3rnos** [comment]
> Sorry about your changes in the README file. I didn't mean to ignore your effort. I just tried to reorder your changes and update the keyword. The issue about getOverrides() occurred due to my hurry. I tried to stabilize the changes you need faster to publish the package and make it available sooner because I have limited free time during the week.

No problem at all, I appreciated your quick publishing since I couldn't just use my fork in production.

> About the getOverrides:
Having an issue will help to track and fix it. Generally, I think it's better to have that like getOverrides() rather than getOverrides({}) as it is more readable, and the curly braces are useless here. What do you think?

Yes, I also agree with you. I'll open a new pull request then!

**Comment by HPouyanmehr** [comment]
Thanks a lot @Et3rnos,

I'll merge it and update the package.

**Pull request merged**
